export const GlobalState = {
  correlatives: [],
  degrees: [],
  professors: {},
  pursuetypes: {},
  roles: {},
  shifts: {},
  studyplans: {},
  subjects: {},
  subjectsxstudyplan: {},
  students: {},
  studentxsubjectsxstudyplan: {},
  test: [],
  testtypes: {},
  userLogin: {},
  users: [],
  loading: false,
  error: false,
  message: ""
};
